config/routes.rb
Rails.application.routes.draw do
  root 'site#home'
  get '/contact' => 'site#contact'

  resources :projects, only: [:index, :show, :new, :create] do
    resources :entries, only: [:index, :new, :create]
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project
  validates :hours, presence: true, numericality: true 
  validates :minutes, presence: true, numericality: true
  validates :date, presence: true
  validates :project, presence: true
   def self.calculate_hours(project)
    @entries = project.entries.where("created_at > ?", 1.month.ago)
    total = 0
    @entries.each do |entry|
      total += entry.hours*60 + entry.minutes
    end
    @total = (total/60.0).round(2)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :entries
  validates :name, presence: true, uniqueness: true, length: {maximum: 30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @project = Project.find params[:project_id]
    @entries = @project.entries
  
    @total = Entry.calculate_hours(@project)
  rescue ActiveRecord::RecordNotFound 
    render 'no_entries_found'
  end
  def new
    @project = Project.find params[:project_id]
    @entry = @project.entries.new
  end
  def create
   @project = Project.find params[:project_id]
   @entry = @project.entries.new entry_params
     if @entry.save
      redirect_to action: 'index', controller: 'entries', project_id: @project.id
     else
      @errors = @entry.errors.full_messages
      render "new"
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.order(created_at: :desc).limit(10)
  end

  def show 
    @project = Project.find params[:id]
  rescue ActiveRecord::RecordNotFound 
    render 'no_projects_found'
  end
  def new
    @project= Project.new
  end
  def create
    @project = Project.new project_params
    if @project.save
      redirect_to action: 'index', controller: 'projects'
    else
      @errors = @project.errors.full_messages
      render "new"
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/index.html.erb
<h1><%= @project.name %></h1>

<h2><%= @total %> hours worked this month </h2>

<%=link_to("Create new entry", new_project_entry_path) %>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <p>
      <%= entry.date.strftime('%a %d %b %Y') %>
      <br>
      <%= entry.hours %> hours and <%= entry.minutes %> minutes 
      <br>
      -- <%= entry.comments %> --
      </p>
    </li>
  <% end %>
</ul>

app/views/entries/new.html.erb
<h1> Project: <%= @project.name %> </h1>
<h3>Create New Entry</h3> 


<% if @entry.errors.any? %>
  <% @errors.each do |error| %> 
    <ul> <span style="color:red"><%= error %> </span> </ul>
  <% end %>
<% end %>

<%= form_for [@project, @entry] do |f| %>

  <p><%= f.label :hours %> <%= f.text_field :hours %> </p>
  <p><%= f.label :minutes %> <%= f.text_field :minutes %> </p>
  <p><%= f.label :date %> <%= f.date_field :date %> </p>

  <%= f.submit 'Save' %>

<% end %>

<p><%=link_to("Cancel", project_entries_path) %></p>

app/views/entries/no_entries_found.html.erb
<h1>We didn't find your entry, but we did find this cute kitten.</h1>
<img src="/kitten.jpg">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimetrackingRebuild</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to("Home", root_path) %>
<%= link_to("Contact us", contact_path) %>
<%=link_to("View projects", projects_path) %>

<%= yield %>



</body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<h3> <%= link_to("Create new project", new_project_path)%> </h3>

<% @projects.each do |project| %>
  <ul>
    <li> 
    <h4><%= link_to(project.name, project_entries_path(project)) %></h4>
      <% if project.description.present? %> 
        <%= project.description %>
      <% end %>
    </li>
    
  </ul>
<% end %>

app/views/projects/new.html.erb
<h1>Create New Project</h1>

<%= @errors %>

<%= form_for [@project] do |f| %>

  <p><%= f.label :name %> <%= f.text_field :name %> </p>
  <p><%= f.label :description %> <%= f.text_field :description %> </p>

  <%= f.submit 'Save' %>

<% end %>

<p><%=link_to("Cancel", root_path) %></p>

app/views/projects/no_projects_found.html.erb
<h1>We didn't find your project, but we did find this cute kitten.</h1>
<img src="/kitten.jpg">

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>

app/views/site/contact.html.erb
<h1>Contact us</h1>
<p>contact@example.com</p>

app/views/site/home.html.erb
<h1> Welcome to this timetracking tool</h1>

<h3> <%= link_to("Create new project", new_project_path)%> </h3>